---
titlepage-logo: "img/fhdw.png"

##########################################################
###### Die folgenden Angaben bitte anpassen
Organisation: FHDW Paderborn
Studiengang: Angewandte Informatik (B.Sc.)
# Dokumententyp: "Bachelorthesis" # oder: "Praxisarbeit" etc.
Dokumententyp: "Studienarbeit im Modul Weiterführende Datenbankkonzepte"
Titel: Exemplarisches Beispiel für eine Demonstration von Quarto
Verfasser: | # für Titelseite
  \textbf{Friedrich Fleißigerstudent}\
  Fürstenallee 3-6\
  33102 Paderborn
Pruefer: | 
  Prof. Dr. Weis-Alles\
  Prof. Dr. Besser\
Abgabedatum: 2024-05-67

# für Ehrenwörtliche Erklärung
Autor: Friedrich Fleißigerstudent 
AutorUnterschrift: "img/Mustermann.png"
Ort: Paderborn

# für Sperrvermerk...
Kooperationsunternehmen: Wieauchimmer\-IstGeheim GmbH
##########################################################

glossary:
  path: glossary.yml
  popup: click
  show: true

jupyter: python3
format:
  pdf:
    default: true
    sperrvermerk: false # true #
    gendervermerk: true #false #
    glossar: true #false #
    keep-tex: true #false #true #
    latex-tinytex: false #true #  
  html:
    lang: de
---

<!-- Das Dokument beginnt hier: -->

\% Diesen Kommentar bitte nicht entfernen!

<!-- Mittels include-Anweisungen werden weitere qmd-Dateien eingebunden -->

{{< include Einleitung.qmd >}}

{{< include Hauptteil.qmd >}}

<!-- Anhang -->

\appendix
\renewcommand{\thefigure}{A\arabic{figure}}
\renewcommand{\thetable}{A\arabic{table}}
\setcounter{figure}{0}
\setcounter{table}{0}

# Erster Anhang

Dieser Code-Block kann verwendet werden, um die aktuell aktive Python-Installation zu bestimmen:

```{python}
#| eval: true
#| code-line-numbers: true
import sys
print(sys.executable)
print(sys.version)
```

# Zweiter Anhang

Der zweite Anhang enthält eine Tabelle:

| Col1 | Col2 | Col3 |
|------|------|------|
| 1    | 2    | 3    |
| 4    | 5    | 6    |
| 7    | 8    | 9    |

: Alle Zahlen von 1..9 {#tbl-numbers}

# Struktur der Vorlage

Folgende Dateien werden von dieser Vorlage verwendet.

-   Hauptdatei `fhdwVorlage.qmd` (bzw. `MeineArbeit.qmd` bzw. eine entsprechende Kopie)
    -   `Einleitung.qmd` (bzw. `MeineArbeit01.qmd` bzw. eine entsprechende Kopie)
    -   `Hauptteil.qmd` (bzw. `MeineArbeit02.qmd` bzw. eine entsprechende Kopie)
    -   `_quarto.yml`
        -   `before-body.tex`
        -   `_titlepage.tex`
        -   `toc.tex`
        -   `after-body.tex`
        -   `in-header.tex`
    -   `references.csl`

Hier ein Verweis auf @fig-mustermann mit der Unterschrift von Max Mustermann. Die Abbildung befindet sich in einer anderen Datei.

# Quellen {.unnumbered}

::: {#refs}
:::
